trigger:
  batch: true
  branches:
    include:
      - main

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: "ttrunck-acr"
  imageRepository: "aspnetdevops"
  tag: "$(Build.BuildId)"

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build docker image
            inputs:
              command: "build"
              Dockerfile: "**/Dockerfile"
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              tags: |
                $(tag)
          - task: DockerCompose@0
            displayName: Run services
            inputs:
              dockerComposeFile: "docker-compose.yaml"
              action: Run services
              projectName: $(Build.Repository.Name)
              qualifyImageNames: true
              buildImages: false
              abortOnContainerExit: true
              detached: true
          - task: Bash@3
            displayName: Integration tests
            inputs:
              targetType: "inline"
              script: "wget --spider --no-verbose --retry-connrefused --tries=5 http://localhost/health  || exit 1"
          - task: Docker@2
            displayName: Push docker image
            inputs:
              containerRegistry: $(dockerRegistryServiceConnection)
              repository: $(imageRepository)
              command: "push"
              tags: |
                $(tag)

          - publish: manifests
            artifact: manifests
