apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetdevops
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetdevops
  template:
    metadata:
      labels:
        app: aspnetdevops
    spec:
      containers:
        - name: aspnetdevops
          image: ttrunck.azurecr.io/aspnetdevops
          env:
            - name: ConnectionStrings__MSSQL
              valueFrom:
                secretKeyRef:
                  name: connection-strings
                  key: MSSQL
          ports:
            - containerPort: 80
